### ISSUE TITLE
frontend npm run build

### ISSUE THREAD

**Issue by dmascheck** [w-okada/flect-chime-sdk-demo#12]

**Comment by dmascheck** [comment]
I have followed the steps for the frontend7 npm run build and getting a webpack error.  How do I resolve?


> frontend7@1.0.0 build
> run-s clean copy:backendinfo copy:backend_types copy:resources webpack:build


> frontend7@1.0.0 clean
> rimraf dist/*


> frontend7@1.0.0 copy:backendinfo
> node bin/importBackendSetting.js

{
  Outputs: [
    {
      OutputKey: 'UserPoolClientId',
      OutputValue: '71c7dakkoh9ch97pcof2it260s',
      Description: 'UserPoolClientId'
    },
    {
      OutputKey: 'UserPoolId',
      OutputValue: 'us-east-1_h0T0Q7h4f',
      Description: 'UserPoolId'
    },
    {
      OutputKey: 'BucketDomainName',
      OutputValue: 'danmascchimebackground-bucket.s3.amazonaws.com',
      Description: 'BucketDomainName'
    },
    {
      OutputKey: 'Bucket',
      OutputValue: 'danmascchimebackground-bucket',
      Description: 'Bucket'
    },
    {
      OutputKey: 'DemoEndpoint',
      OutputValue: 'https://d2kx7udjm8sodg.cloudfront.net',
      Description: 'DemoEndpoint'
    },
    {
      OutputKey: 'RestAPIEndpoint',
      OutputValue: 'https://47jc7oxuj9.execute-api.us-east-1.amazonaws.com/prod/',
      Description: 'RestAPIEndpoint'
    },
    {
      OutputKey: 'CDNComainName',
      OutputValue: 'd2kx7udjm8sodg.cloudfront.net',
      Description: 'CDNComainName'
    },
    {
      OutputKey: 'WebSocketEndpoint',
      OutputValue: 'wss://4xydw6f5yf.execute-api.us-east-1.amazonaws.com',
      Description: 'WebSocketEndpoint'
    },
    {
      OutputKey: 'DistributionId',
      OutputValue: 'E3OHZ074VITXUZ',
      Description: 'DistributionId'
    },
    {
      OutputKey: 'ChimeAPIEndpointA81918E8',
      OutputValue: 'https://47jc7oxuj9.execute-api.us-east-1.amazonaws.com/prod/'
    },
    {
      OutputKey: 'BucketWebsiteDomainName',
      OutputValue: 'danmascchimebackground-bucket.s3-website-us-east-1.amazonaws.com',
      Description: 'BucketWebsiteDomainName'
    }
  ]
}
Outputs
[
  {
    OutputKey: 'UserPoolClientId',
    OutputValue: '71c7dakkoh9ch97pcof2it260s',
    Description: 'UserPoolClientId'
  },
  {
    OutputKey: 'UserPoolId',
    OutputValue: 'us-east-1_h0T0Q7h4f',
    Description: 'UserPoolId'
  },
  {
    OutputKey: 'BucketDomainName',
    OutputValue: 'danmascchimebackground-bucket.s3.amazonaws.com',
    Description: 'BucketDomainName'
  },
  {
    OutputKey: 'Bucket',
    OutputValue: 'danmascchimebackground-bucket',
    Description: 'Bucket'
  },
  {
    OutputKey: 'DemoEndpoint',
    OutputValue: 'https://d2kx7udjm8sodg.cloudfront.net',
    Description: 'DemoEndpoint'
  },
  {
    OutputKey: 'RestAPIEndpoint',
    OutputValue: 'https://47jc7oxuj9.execute-api.us-east-1.amazonaws.com/prod/',
    Description: 'RestAPIEndpoint'
  },
  {
    OutputKey: 'CDNComainName',
    OutputValue: 'd2kx7udjm8sodg.cloudfront.net',
    Description: 'CDNComainName'
  },
  {
    OutputKey: 'WebSocketEndpoint',
    OutputValue: 'wss://4xydw6f5yf.execute-api.us-east-1.amazonaws.com',
    Description: 'WebSocketEndpoint'
  },
  {
    OutputKey: 'DistributionId',
    OutputValue: 'E3OHZ074VITXUZ',
    Description: 'DistributionId'
  },
  {
    OutputKey: 'ChimeAPIEndpointA81918E8',
    OutputValue: 'https://47jc7oxuj9.execute-api.us-east-1.amazonaws.com/prod/'
  },
  {
    OutputKey: 'BucketWebsiteDomainName',
    OutputValue: 'danmascchimebackground-bucket.s3-website-us-east-1.amazonaws.com',
    Description: 'BucketWebsiteDomainName'
  }
]
create sync.sh
bucket: undefined
generate access url
generate invalidation script

> frontend7@1.0.0 copy:backend_types
> cp ../backend2/lib/lambda2/http_request.ts src/http_request.ts


> frontend7@1.0.0 copy:resources
> node bin/list_resources.js && mkdir -p dist && cp -r public/* dist/


> frontend7@1.0.0 webpack:build
> webpack --config webpack.config.js


[35m🌼 daisyUI components 2.15.3[0m [0m https://github.com/saadeghi/daisyui
  [32m✔︎ Including:[0m [0m base, components, themes[29], utilities
  

[35m🌼 daisyUI components 2.15.3[0m [0m https://github.com/saadeghi/daisyui
  [32m✔︎ Including:[0m [0m base, components, themes[29], utilities
  
asset index.js 11.8 MiB [emitted] (name: main)
asset ./index.html 615 bytes [emitted]
orphan modules 111 KiB [orphan] 41 modules
runtime modules 1.31 KiB 8 modules
modules by path ./node_modules/ 9.79 MiB 699 modules
modules by path ./src/ 379 KiB
  modules by path ./src/100_components/ 120 KiB 19 modules
  modules by path ./src/001_clients_and_managers/ 91.9 KiB 16 modules
  modules by path ./src/002_hooks/ 50.4 KiB 9 modules
  modules by path ./src/000_css/*.css 101 KiB 4 modules
  modules by path ./src/*.tsx 1.68 KiB 2 modules
  modules by path ./src/*.css 7.83 KiB 2 modules
  modules by path ./src/*.ts 821 bytes 2 modules
  + 2 modules
optional modules 30 bytes [optional]
  crypto (ignored) 15 bytes [optional] [built] [code generated]
  crypto (ignored) 15 bytes [optional] [built] [code generated]

ERROR in ./src/BackendConfig.ts
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/danmasc/Documents/GitHub/flect-chime-sdk-demo/frontend7/src/BackendConfig.ts: Unexpected token (1:13)

> 1 | export const 0 = "[object Object]" 
    |              ^
  2 | export const 1 = "[object Object]" 
  3 | export const 2 = "[object Object]" 
  4 | export const 3 = "[object Object]" 
    at instantiate (/Users/danmasc/Documents/GitHub/flect-chime-sdk-demo/frontend7/node_modules/@babel/parser/lib/index.js:72:32)
    at constructor (/Users/danmasc/Documents/GitHub/flect-chime-sdk-demo/frontend7/node_modules/@babel/parser/lib/index.js:358:12)
    at Object.raise (/Users/danmasc/Documents/GitHub/flect-chime-sdk-demo/frontend7/node_modules/@babel/parser/lib/index.js:3341:19)
    at Object.unexpected (/Users/danmasc/Documents/GitHub/flect-chime-sdk-demo/frontend7/node_modules/@babel/parser/lib/index.js:3379:16)
    at Object.parseIdentifierName (/Users/danmasc/Documents/GitHub/flect-chime-sdk-demo/frontend7/node_modules/@babel/parser/lib/index.js:14087:18)
    at Object.parseIdentifier (/Users/danmasc/Documents/GitHub/flect-chime-sdk-demo/frontend7/node_modules/@babel/parser/lib/index.js:14067:23)
    at Object.parseBindingAtom (/Users/danmasc/Documents/GitHub/flect-chime-sdk-demo/frontend7/node_modules/@babel/parser/lib/index.js:11936:17)
    at Object.parseBindingAtom (/Users/danmasc/Documents/GitHub/flect-chime-sdk-demo/frontend7/node_modules/@babel/parser/lib/index.js:10929:22)
    at Object.parseVarId (/Users/danmasc/Documents/GitHub/flect-chime-sdk-demo/frontend7/node_modules/@babel/parser/lib/index.js:15400:20)
    at Object.parseVarId (/Users/danmasc/Documents/GitHub/flect-chime-sdk-demo/frontend7/node_modules/@babel/parser/lib/index.js:10681:11)
 @ ./src/003_provider/AppStateProvider.tsx 3:0-64 30:16-26 31:22-38
 @ ./src/index.tsx 4:0-67 7:46-62

webpack 5.73.0 compiled with 1 error in 3473 ms

**Comment by w-okada** [comment]
please tell me node version.

**Comment by dmascheck** [comment]
v16.13.1

**Comment by w-okada** [comment]
please run 
```
$ node bin/importBackendSetting.js
```
and 
```
$ cat src/BackendConfig.ts
```
What style of text is output?

In my environment, I got as follows.
```
export const DemoEndpoint = "https://xxxxx"
export const DistributionId = "xxxx"
```

**Comment by w-okada** [comment]
no response. close
